Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "test" do |test|

    test.vm.box = "ubuntu/bionic64"
    test.vm.network :private_network, ip: "192.168.56.20" 
    test.vm.provision :shell, path: "setup.sh"
 
    test.vm.provider :virtualbox do |v|
      v.name = "test"
      v.memory = 2048
    end

  end

end
