Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "nginx" do |nginx|

    nginx.vm.box = "ubuntu/bionic64"
    nginx.vm.network :private_network, ip: "192.168.56.20" 
    nginx.vm.provision :shell, path: "nginx.sh"
 
    nginx.vm.provider :virtualbox do |v|
      v.name = "nginx"
      v.memory = 2048
    end

  end

end
